FROM ubuntu
# FROM nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y git python3 python3-pip r-base r-cran-ggplot2 \
        wget libncurses5-dev zlib1g-dev libbz2-dev liblzma-dev libcurl3-dev \
    && apt-get clean

RUN pip3 install multiqc \
    cutadapt

# RUN cpan Statistics::Basic

# conda
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/src/miniconda3 \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
ENV PATH=${PATH}:/usr/src/miniconda3/bin

RUN conda config --add channels bioconda \
    && conda install -y -c bioconda fastqc bwa samtools=1.9 bismark=0.23.0 preseq bedtools

WORKDIR /usr/src
#trim_galore
RUN curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.6.tar.gz -o trim_galore.tar.gz \
    && tar xvzf trim_galore.tar.gz \
    && rm trim_galore.tar.gz \
    && cd TrimGalore-0.6.6/ \
    && mv trim_galore /usr/src/miniconda3/bin/
